In [7]:
#@title setup
!pip install -q datasets trafilatura justext fasttext huggingface_hub transformers torch pandas

import html
from bs4 import BeautifulSoup
from IPython.display import display, HTML
from datasets import load_dataset
import pandas as pd
import os
import json
from datasets import load_dataset
import urllib.request
import textwrap
from torch.utils.data import IterableDataset, DataLoader

# 1) Common Crawl Samples

In [ ]:
common_crawl_dataset = load_dataset("agentlans/common-crawl-sample",
                                    split="train",
                                    streaming=True)

target_snippets = [
    "christianity.stackexchange.com/questions/1977",
    "slideshare.net",
    "englewoodwater.com"
]

matched_records = []
scanned = 0
max_search = 5000

print("Searching dataset for target URLs using substring matching...")
for record in common_crawl_dataset:
    scanned += 1
    if scanned % 1000 == 0:
        print(f"Scanned {scanned} records...")

    url = record.get("url", record.get("uri", ""))
    if any(snippet in url for snippet in target_snippets):
        record["url"] = url  # Ensure the 'url' key exists for the DataFrame
        matched_records.append(record)
        print(f"Found: {url}")

    if len(matched_records) >= len(target_snippets):
        print("All targets found!")
        break

    if scanned >= max_search:
        print(f"Reached maximum search limit ({max_search}) without finding all URLs.")
        break

if matched_records:
    cc_samples_df = pd.DataFrame(matched_records)
    display(cc_samples_df[["url", "text"]].style.set_properties(**{"white-space": "pre-wrap", "text-align": "left", "max-width": "600px"}))
else:
    print("No records matched the target URLs in the scanned sample.")

Searching dataset for target URLs using substring matching...
Found: http://englewoodwater.com/
Found: http://www.slideshare.net/errino/project-server-in-the-oil-and-gas-industry-enabling-technologies-best-practices
Found: http://christianity.stackexchange.com/questions/1977/is-it-hypocritical-to-be-a-christian-and-also-be-against-welfare/2055
All targets found!

In [ ]:
from IPython.display import display, HTML

iframe_urls = [
    "https://englewoodwater.com/",
]

for url in iframe_urls:
    display(HTML(f'<h4>{url}</h4><iframe src="{url}" width="100%" height="400" style="border:1px solid #ccc; border-radius:4px;"></iframe>'))

# 2) HTML Is Messy

In [ ]:
raw_html_response = urllib.request.urlopen("https://englewoodwater.com/")
raw_html_bytes = raw_html_response.read()
raw_html_text = raw_html_bytes.decode("utf-8", errors="replace")

# Use BeautifulSoup to find the specific divs
soup = BeautifulSoup(raw_html_text, "html.parser")
target_divs = soup.select('div#Content[role="main"]')

if target_divs:
    extracted_html = "\n\n".join(str(div) for div in target_divs)
else:
    extracted_html = "No matching divs found."

# Save to a local text file
with open("target_divs.html", "w", encoding="utf-8") as f:
    f.write(extracted_html)

# Escape the HTML so it displays as raw code instead of rendering
escaped_html = html.escape(extracted_html)
display(HTML(f'<div style="max-height: 500px; overflow-y: auto; background: #f5f5f5; padding: 10px; border: 1px solid #ccc;"><pre style="white-space: pre-wrap; word-wrap: break-word;">{escaped_html}</pre></div>'))
print(f"\n... ({len(extracted_html):,} total characters in extracted divs saved to 'target_divs.html')")

... (17,135 total characters in extracted divs saved to 'target_divs.html')

# 3) Clean Up the HTML

### 3.1) Trafilatura Extraction

In [ ]:
import trafilatura
import textwrap

trafilatura_extracted = trafilatura.extract(raw_html_text)
print("=" * 80)
print("TRAFILATURA OUTPUT")
print("=" * 80)
if trafilatura_extracted:
    print(textwrap.fill(trafilatura_extracted[:2000], width=80))
else:
    print("No content extracted")
print()

================================================================================
TRAFILATURA OUTPUT
================================================================================
Welcome to Englewood Water District Delivering High Quality, Clean Water While
Protecting Our Environment Englewood Water District (Englewood, FL) The District
encompasses approximately 44.5 square miles in Southern Sarasota County and
Western Charlotte County. There are four (4) fresh water and two (2) brackish
water wellfields. This raw water is treated at either the lime softening
treatment plant or the reverse osmosis treatment plant. The finished waters are
mixed and sent into the distribution system. The District also operates a 3.0
MGD Water Reclamation Facility to take care of the sanitary sewer needs of the
area. As of January 2019 87% of all water customers also receive sewer service.
In 2023 customers within the Englewood Water District service area used an
estimated 75 gallons per capita per day (gpcd). To see how your water usage
stacks up please visit SWFWMD Water Use Calculator.

### 3.2) Justext Extraction

In [ ]:
import justext
import textwrap

justext_paragraphs = justext.justext(raw_html_bytes, justext.get_stoplist("English"))
justext_extracted = "\n".join([p.text for p in justext_paragraphs if not p.is_boilerplate])
print("=" * 80)
print("JUSTEXT OUTPUT")
print("=" * 80)
if justext_extracted:
    print(textwrap.fill(justext_extracted[:2000], width=80))
else:
    print("No content extracted")
print()

================================================================================
JUSTEXT OUTPUT
================================================================================
Assistance paying utility bills may be available. Sarasota County residents can
view information on the Emergency Rental Assistance Program here. Charlotte
County residents can view information on the Fastrack Program here. Reminder —
Please do not flush items down toilets that do not belong there. Items such as
Paper Towels, Wipes (such as Baby Wipes, Disinfecting Wipes, etc..) and Cloth
Rags can cause problems for sewer collection systems. These items can also cause
blockages in a households own sewer pipes, which could cause sewer to back up
into peoples homes. Items such as these should be discarded in the trash.
Wastewater that comes from flushing should only contain water, human waste and
toilet paper. Englewood Water District (Englewood, FL) The District encompasses
approximately 44.5 square miles in Southern Sarasota County and Western
Charlotte County. There are four (4) fresh water and two (2) brackish water
wellfields. This raw water is treated at either the lime softening treatment
plant or the reverse osmosis treatment plant. The finished waters are mixed and
sent into the distribution system. The District also operates a 3.0 MGD Water
Reclamation Facility to take care of the sanitary sewer needs of the area. As of
January 2019 87% of all water customers also receive sewer service. In 2023
customers within the Englewood Water District service area used an estimated 75
gallons per capita per day (gpcd). To see how your water usage stacks up please
visit SWFWMD Water Use Calculator.

### 3.3) Naive HTML Stripper

In [ ]:
from html.parser import HTMLParser
import textwrap

class NaiveHTMLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self.fed = []
        self.skip_tags = {"script", "style", "noscript"}
        self.current_skip = False
    def handle_starttag(self, tag, attrs):
        if tag in self.skip_tags:
            self.current_skip = True
    def handle_endtag(self, tag):
        if tag in self.skip_tags:
            self.current_skip = False
    def handle_data(self, data):
        if not self.current_skip:
            self.fed.append(data)
    def get_text(self):
        return " ".join("".join(self.fed).split())

naive_stripper = NaiveHTMLStripper()
naive_stripper.feed(raw_html_text)
naive_stripped_text = naive_stripper.get_text()

print("=" * 80)
print("NAIVE STRIP-TAGS OUTPUT (simulates raw WET file)")
print("=" * 80)
print(textwrap.fill(naive_stripped_text[:2000], width=80))
print()

================================================================================
NAIVE STRIP-TAGS OUTPUT (simulates raw WET file)
================================================================================
Englewood Water District - Englewood FL 941-474-3217866-460-1080 Home CodeRED
About Us Administration Board of Supervisors Board of Supervisors Meetings
Employee Benefits Committee Meetings Biography Supervisor Election District Maps
Important Documents Customer Service Hurricane Frequently Asked Questions How to
check for a leak Reading Your Bill Reading the meter Disconnect Policy Water
Restrictions Rates Finance Financial Information Defined Benefit Pension Report
EWD Actuarial Fact Sheet MyFlorida Actuarial Fact Sheet Operations Laboratory
Drinking Water Standards Annual Water Report Water Production Well Fields
Reverse Osmosis Plant Lime Softening Plant Distribution Chromium: Frequently
Asked Questions Wastewater Treatment Collections System Reclamation Plant
Reclaimed Water System Reclaimed Water Frequently Asked questions (FAQ)
Engineering Developer’s Info Project Preliminary Submittal List Project
Certification Submittal List Project Submittal Form Details Construction
Standards EWD Public Web Map EWD Facilities Plan Master Plans 2024 Potable Water
Master Plan Update Potable Water Master Plan Update Appendix A Appendix B
Appendix C Appendix D 2022 Reuse Master Plan Update Reuse Master Plan Update
2021 Sewer Master Plan Update Sewer Master Plan Update Executive Summary
Appendix A Appendix B Appendix C Appendix D 2017 Utility Master Plan Utility
Master Plan Final Appendix A Appendix B Appendix C Appendix D Appendix E
Purchasing Forms Assessment Pay Off Autopay Application Billing Adjustment
Request Email Notification Request Hydrants Fire Flow Test Form Temporary Water
Meter Mailing Address Change Rental Agreement Seasonal On/Off Service
Availability Transfer Service Water/Sewer Hookup Assistance Program Sarasota
County Charlotte County Watering Violations Backflow Backflow Test Entry
Backflow Frequently Asked Questions Certified Backflow Tester List Backflow
Resolution Cross Connection Control & Backflow Prevention Program Manual
Employment Employment Opportu

### 3.4) Side-by-Side Comparison

In [ ]:
from IPython.display import display, HTML
import html

# Safely extract a portion of text for comparison
t_text = html.escape((trafilatura_extracted or "")[:1500]) + ("..." if trafilatura_extracted and len(trafilatura_extracted) > 1500 else "")
j_text = html.escape((justext_extracted or "")[:1500]) + ("..." if justext_extracted and len(justext_extracted) > 1500 else "")
n_text = html.escape((naive_stripped_text or "")[:1500]) + ("..." if naive_stripped_text and len(naive_stripped_text) > 1500 else "")

table_html = f"""
<table style="width:100%; text-align:left; border-collapse: collapse; border: 1px solid #ccc;">
    <tr style="background-color: #f2f2f2;">
        <th style="padding: 10px; border: 1px solid #ccc; width: 33%;">Trafilatura</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33%;">Justext</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33%;">Naive HTML Stripper</th>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{t_text}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{j_text}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{n_text}</pre></td>
    </tr>
</table>
"""

display(HTML(table_html))

# 4) FineWeb-Edu Samples (Streaming)

In [ ]:
from datasets import load_dataset
import pandas as pd

fineweb_edu_stream = load_dataset(
    "HuggingFaceFW/fineweb-edu",
    name="sample-100BT",
    split="train",
    streaming=True,
)

fineweb_edu_samples = []
for record in fineweb_edu_stream:
    fineweb_edu_samples.append(record)
    if len(fineweb_edu_samples) == 3:
        break

fineweb_edu_df = pd.DataFrame(fineweb_edu_samples)
display(
    fineweb_edu_df[["url", "text", "score"]]
    .style.set_properties(**{"white-space": "pre-wrap", "text-align": "left", "max-width": "600px"})
    .set_properties(subset=["url"], **{"width": "10%"})
)

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/2410 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/140 [00:00<?, ?it/s]

# 5) Quality Filtering: fastText DCLM Classifier

In [ ]:
import fasttext
from huggingface_hub import hf_hub_download

dclm_model_path = hf_hub_download(
    repo_id="mlfoundations/fasttext-oh-eli5",
    filename="openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train.bin",
)

dclm_classifier = fasttext.load_model(dclm_model_path)

def dclm_quality_score(text, classifier=dclm_classifier):
    cleaned = text.replace("\n", " ").strip()[:5000]
    # Bypass the buggy wrapper to avoid NumPy 2.0 error
    predictions = classifier.f.predict(cleaned, 1, 0.0, "")
    probability, label = predictions[0]
    if label == "__label__hq":
        return probability
    else:
        return 1.0 - probability

print("=" * 60)
print("DCLM SCORES — Common Crawl Samples")
print("=" * 60)
for _, row in cc_samples_df.iterrows():
    score = dclm_quality_score(row["text"])
    print(f"  {score:.4f}  {row['url'][:80]}")

print()
print("=" * 60)
print("DCLM SCORES — FineWeb-Edu Samples")
print("=" * 60)
for _, row in fineweb_edu_df.iterrows():
    score = dclm_quality_score(row["text"])
    print(f"  {score:.4f}  {row['url'][:80]}")

============================================================
DCLM SCORES — Common Crawl Samples
============================================================
  -0.0000  http://englewoodwater.com/
  0.0003  http://www.slideshare.net/errino/project-server-in-the-oil-and-gas-industry-enab
  0.5719  http://christianity.stackexchange.com/questions/1977/is-it-hypocritical-to-be-a-

============================================================
DCLM SCORES — FineWeb-Edu Samples
============================================================
  0.0278  http://austenauthors.net/the-independent-jane
  0.2146  http://cloudyandcool.com/2009/05/05/wind-shear-and-tornadoes/
  0.0083  http://cogweb.ucla.edu/ep/FluteDebate.html

# 6) Quality Filtering: FineWeb-Edu Classifier

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

fineweb_classifier_name = "HuggingFaceFW/fineweb-edu-classifier"
fineweb_tokenizer = AutoTokenizer.from_pretrained(fineweb_classifier_name)
fineweb_quality_model = AutoModelForSequenceClassification.from_pretrained(fineweb_classifier_name)
fineweb_quality_model.eval()

def fineweb_edu_quality_score(text, tokenizer=fineweb_tokenizer, model=fineweb_quality_model):
    truncated = text[:2000]
    tokens = tokenizer(truncated, return_tensors="pt", padding=True, truncation=True, max_length=512)
    with torch.no_grad():
        score = model(**tokens).logits.squeeze(-1).item()
    return round(score, 4)

print("=" * 60)
print("FINEWEB-EDU SCORES — Common Crawl Samples")
print("=" * 60)
for _, row in cc_samples_df.iterrows():
    score = fineweb_edu_quality_score(row["text"])
    print(f"  {score:.4f}  {row['url'][:80]}")

print()
print("=" * 60)
print("FINEWEB-EDU SCORES — FineWeb-Edu Samples")
print("=" * 60)
for _, row in fineweb_edu_df.iterrows():
    score = fineweb_edu_quality_score(row["text"])
    print(f"  {score:.4f}  {row['url'][:80]}")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

============================================================
FINEWEB-EDU SCORES — Common Crawl Samples
============================================================
  1.6884  http://englewoodwater.com/
  1.1438  http://www.slideshare.net/errino/project-server-in-the-oil-and-gas-industry-enab
  1.1081  http://christianity.stackexchange.com/questions/1977/is-it-hypocritical-to-be-a-

============================================================
FINEWEB-EDU SCORES — FineWeb-Edu Samples
============================================================
  2.8415  http://austenauthors.net/the-independent-jane
  4.0641  http://cloudyandcool.com/2009/05/05/wind-shear-and-tornadoes/
  3.5170  http://cogweb.ucla.edu/ep/FluteDebate.html

# 7) Preparing N+1 pairs for training

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokens = tokenizer(justext_extracted)["input_ids"]

inputs = []
targets = []

# Group into small sequences (e.g., 7 tokens) for demonstration
seq_length = 7
for i in range(0, len(tokens) - seq_length, seq_length):
    # Grab a chunk of size seq_length + 1
    chunk = tokens[i : i + seq_length + 1]

    if len(chunk) == seq_length + 1:
        # Input is everything except the last token
        inputs.append(chunk[:-1])
        # Target is everything except the first token (shifted by 1)
        targets.append(chunk[1:])


print("--- First Pair ---")
print(f"Input IDs:  {inputs[0]}")
print(f"Target IDs: {targets[0]}\n")

print(f"Decoded Input:  {repr(tokenizer.decode(inputs[0]))}")
print(f"Decoded Target: {repr(tokenizer.decode(targets[0]))}")

--- First Pair ---
Input IDs:  [8021, 9311, 5989, 10361, 9024, 743, 307]
Target IDs: [9311, 5989, 10361, 9024, 743, 307, 1695]

Decoded Input:  'Assistance paying utility bills may be'
Decoded Target: 'istance paying utility bills may be available'

# 7) Exercise: fetch a website's HTML, try all three text extractors, and compare quality

In [ ]:
#@title Answer
# 1. Define the target URL and fetch the HTML
target_url = "https://en.wikipedia.org/wiki/Web_scraping"
print(f"Fetching HTML from: {target_url}")

req = urllib.request.Request(target_url, headers={'User-Agent': 'Mozilla/5.0'})
with urllib.request.urlopen(req) as response:
    raw_bytes = response.read()
    raw_text = raw_bytes.decode('utf-8', errors='replace')

# 2. Extract text using Trafilatura
print("Extracting using Trafilatura...")
ext_traf = trafilatura.extract(raw_text) or "No content extracted"

# 3. Extract text using Justext
print("Extracting using Justext...")
paragraphs = justext.justext(raw_bytes, justext.get_stoplist("English"))
ext_just = "\n".join([p.text for p in paragraphs if not p.is_boilerplate]) or "No content extracted"

# 4. Extract text using the Naive HTML Stripper defined earlier in the notebook
print("Extracting using Naive HTML Stripper...")
my_stripper = NaiveHTMLStripper()
my_stripper.feed(raw_text)
ext_naive = my_stripper.get_text()

# 5. Quality Filtering
print("Calculating quality scores...")
traf_dclm = dclm_quality_score(ext_traf)
just_dclm = dclm_quality_score(ext_just)
naive_dclm = dclm_quality_score(ext_naive)

traf_fw = fineweb_edu_quality_score(ext_traf)
just_fw = fineweb_edu_quality_score(ext_just)
naive_fw = fineweb_edu_quality_score(ext_naive)

# 6. Display a side-by-side comparison table
print("Generating comparison table...\n")
def truncate_and_escape(text, length=200):
    safe_text = html.escape((text or "")[:length])
    return safe_text + ("..." if len(text or "") > length else "")

table_html = f"""
<table style="width:100%; text-align:left; border-collapse: collapse; border: 1px solid #ccc; table-layout: fixed;">
    <tr style="background-color: #f2f2f2;">
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Trafilatura</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Justext</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Naive HTML Stripper</th>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_traf)}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_just)}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_naive)}</pre></td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_traf):,}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_just):,}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_naive):,}</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {traf_dclm:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {just_dclm:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {naive_dclm:.4f}</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {traf_fw:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {just_fw:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {naive_fw:.4f}</td>
    </tr>
</table>
"""
display(HTML(table_html))

Fetching HTML from: https://en.wikipedia.org/wiki/Web_scraping
Extracting using Trafilatura...
Extracting using Justext...
Extracting using Naive HTML Stripper...
Calculating quality scores...
Generating comparison table...

# 8) Sharding FineWeb-Edu for Local Storage (Faster Training)

In [4]:
shards_output_dir = "/mnt/user-data/outputs/shards"
os.makedirs(shards_output_dir, exist_ok=True)

# Configuration for our local shards
records_per_shard = 1000
max_shards = 5

fineweb_stream = load_dataset(
    "HuggingFaceFW/fineweb-edu",
    name="sample-100BT",
    split="train",
    streaming=True,
)

shard_index = 0
records_in_current_shard = 0
current_file = open(os.path.join(shards_output_dir, f"shard_{shard_index:03d}.jsonl"), "w", encoding="utf-8")

print(f"Writing to shard {shard_index}...")
for record in fineweb_stream:
    # Storing just the text and url for demonstration to keep sizes manageable
    out_record = {"url": record["url"], "text": record["text"]}
    current_file.write(json.dumps(out_record) + "\n")
    records_in_current_shard += 1

    # If the shard is full, close it and open the next one
    if records_in_current_shard >= records_per_shard:
        current_file.close()
        shard_index += 1

        if shard_index >= max_shards:
            break

        records_in_current_shard = 0
        print(f"Writing to shard {shard_index}...")
        current_file = open(os.path.join(shards_output_dir, f"shard_{shard_index:03d}.jsonl"), "w", encoding="utf-8")

if not current_file.closed:
    current_file.close()

print(f"\nSuccessfully saved {max_shards} shards with {records_per_shard} records each.")
print(f"Files saved to {shards_output_dir}/")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/2410 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/140 [00:00<?, ?it/s]

Writing to shard 0...
Writing to shard 1...
Writing to shard 2...
Writing to shard 3...
Writing to shard 4...

Successfully saved 5 shards with 1000 records each.
Files saved to /mnt/user-data/outputs/shards/

# 9) Resuming 4,000 documents in, with binning

In [5]:
import os
import json

shard_index_to_read = 4
shard_file = os.path.join(shards_output_dir, f"shard_{shard_index_to_read:03d}.jsonl")

global_start_index = shard_index_to_read * records_per_shard

print(f"{shard_file} shard starts at global record {global_start_index + 1}\n")

with open(shard_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        record = json.loads(line)
        global_record_num = global_start_index + i + 1

        print(f"Global Record {global_record_num}:")
        print(f"URL: {record['url']}")
        print(f"Text Snippet: {record['text'][:300]}...\n")
        print("-" * 80 + "\n")

/mnt/user-data/outputs/shards/shard_004.jsonl shard starts at global record 4001

Global Record 4001:
URL: http://www.usaid.gov/results-data/success-stories/saving-newborns-rural-afghanistan
Text Snippet: Miriam has four children, although she has given birth six times. Two infants unfortunately died within days of birth. However, her most recent birth was different in that Miriam and her female relatives had learned from the local female community health worker (CHW) about the importance of keeping ...

--------------------------------------------------------------------------------

Global Record 4002:
URL: http://apnews.excite.com/article/20110219/D9LG45NO0.html
Text Snippet: Cosmic census finds crowd of planets in our galaxy
Feb 19, 5:23 PM (ET)
By SETH BORENSTEIN
WASHINGTON (AP) - Scientists have estimated the first cosmic census of planets in our galaxy and the numbers are astronomical: at least 50 billion planets in the Milky Way.
At least 500 million of those planet...

--------------------------------------------------------------------------------

Global Record 4003:
URL: http://asopa.typepad.com/asopa_people/2012/10/a-poets-journey-3-poetic-inspiration-from-human-experience.html
Text Snippet: ‘A POEM SHOULD BE PALPABLE AND MUTE / As a globed fruit’, says Archibald MacLeish in his poem Ars Poetica [‘The art of poetry’].
Poems are very often inspired by our experiences in life and it is part of the challenge of writing poetry to find ways of expressing our thoughts and feelings without men...

--------------------------------------------------------------------------------

Global Record 4004:
URL: http://blog.prideinplymouth.org.uk/category/featured/alan-turing/
Text Snippet: Lesbian Gay Bisexual Trans History Month takes place every year in February. It celebrates the lives and achievements of the LGBT community. 2013 is dedicated to Maths, science and engineering.
LGBT History Month UK have put together a publication that features Lesbian, Gay, Bisexual and Trans pione...

--------------------------------------------------------------------------------

Global Record 4005:
URL: http://centria.di.fct.unl.pt/projects/view.php?code=6232b5ec42f9dc0f25f4f45fd1002a86&t=o&cscd=85ff861d6c46e37ebe256c211f0d0a25
Text Snippet: Software is ubiquitous in modern day life. Software is used in all personal computing devices, but it also supports the Internet and all existing communication networks. Software is also ubiquitous in all forms of transportation, including avionics, automotive, railways and shipping. Software is als...

--------------------------------------------------------------------------------

Global Record 4006:
URL: http://divisbyzero.com/2008/12/18/sharkovskys-theorem/
Text Snippet: In this post I would like to share one of the most surprising, remarkable, and beautiful results in the study of discrete dynamical systems. It relates to an unusual ordering of the positive integers:
First, some definitions. The basic object of study in a discrete dynamical system is the orbit. Let...

--------------------------------------------------------------------------------

Global Record 4007:
URL: http://en.m.wikibooks.org/wiki/Calculus/Continuity
Text Snippet: We are now ready to define the concept of a function being continuous. The idea is that we want to say that a function is continuous if you can draw its graph without taking your pencil off the page. But sometimes this will be true for some parts of a graph but not for others. Therefore, we want to ...

--------------------------------------------------------------------------------

Global Record 4008:
URL: http://en.wikipedia.org/wiki/Second_Constitutional_Era_(Ottoman_Empire)
Text Snippet: Second Constitutional Era
||This article needs additional citations for verification. (July 2012)|
|Part of a series on the|
|History of Turkey|
The Second Constitutional Era (ايکنجى مشروطيت دورى İkinci Meşrûtiyyet Devri) of the Ottoman Empire began shortly after Sultan Abdülhamid II restored the co...

--------------------------------------------------------------------------------

Global Record 4009:
URL: http://english.people.com.cn/90782/8120039.html
Text Snippet: |The warning label on cigarette packaging (U.S. HHS)|
Key Words:cancer;disease; health
>>Failed again? Quit smoking could not be hard
>>Women who quit smoking before middle age can live a decade longer: study
>>Quit smoking before age 40 greatly reduces death risk: study
SHANGHAI'S cancer rate remai...

--------------------------------------------------------------------------------

Global Record 4010:
URL: http://fun.familyeducation.com/hanukkah/passover/55218.html
Text Snippet: Wooden Star of David
Activity for an individual child
Age group: 18-40 months
Duration of activity: 20 minutes
- 6 craft sticks
- White craft glue
- Blue and white tempera paints
- 2 shallow pie tins
Your child will be learning about shapes and geometry while she makes this well-known symbol.
- Show...

--------------------------------------------------------------------------------

Global Record 4011:
URL: http://health.nytimes.com/health/guides/disease/pharyngitis-viral/news-and-features.html
Text Snippet: May 21, 2013
Pharyngitis - Viral
News & Features
Doctors and patients don’t always communicate well, with serious consequences, says Jerome Groopman.
A few studies have provided scientific evidence that a chill won't cause a cold, but perhaps the answer is not so clear cut.
Many experts say that few...

--------------------------------------------------------------------------------

Global Record 4012:
URL: http://jdp-news.blogspot.com/2010_07_01_archive.html
Text Snippet: Patti challenged us to use or adapt the following form to create a poem:
When ____________ you'll find ___________
That __________________ to make
Patti gave us an example, borrowed from Word After Word After Word, by Patricia MacLachlan (p 36):
When cracked you'll find inside
That tuck in snugly to...

--------------------------------------------------------------------------------

Global Record 4013:
URL: http://kwit.org/post/us-officials-syria-has-prepared-several-dozen-chemical-bombs
Text Snippet: Fri December 14, 2012
U.S. Officials: Syria Has Prepared Several Dozen Chemical Bombs
U.S. and allied officials say the forces of embattled Syrian President Bashar Assad have prepared several dozen bombs and shells loaded with the lethal chemical sarin.
The number is a larger estimate than has previ...

--------------------------------------------------------------------------------

Global Record 4014:
URL: http://labtestsonline.org/news/120323glucose-testing/
Text Snippet: A new clinical practice guideline published in the January 2012 issue of the Journal of Clinical Endocrinology and Metabolism includes the recommendation that everyone admitted to the hospital have blood glucose testing performed. The evidence-based guideline was developed by a panel convened by The...

--------------------------------------------------------------------------------

Global Record 4015:
URL: http://moadoph.gov.au/exhibitions/online/dismissed/epilogue.html
Text Snippet: Thirty years on, the rules of the Constitution which allowed for the dismissal of the Whitlam Labor Government remain unchanged. The different readings of the Constitution put forward by Gough Whitlam and Malcolm Fraser in 1975, and of the conventions surrounding the operations of the Constitution, ...

--------------------------------------------------------------------------------

Global Record 4016:
URL: http://npiweb.com/west/ResourceCenter/tabid/10568/CategoryID/17/resourceID/274/Default.aspx
Text Snippet: To help children make the transition from an old home to a new, try to ease some of the initial fear or apprehension by offering information.
- Look up things about the new home online, on maps or in reference books. Make a scavenger hunt or other game out of the activity.
- Have a special goodbye o...

--------------------------------------------------------------------------------

Global Record 4017:
URL: http://orthodoxwiki.org/index.php?title=Joshua_of_Navi&direction=prev&oldid=102227
Text Snippet: Joshua of Navi
Joshua of Navi, was born of the tribe of Ephraim in Egypt, in the seventeenth century before Christ. When he was eighty-five years of age, he became the successor of Moses.  He restrained the flow of the River Jordan and allowed the Israelites to cross on foot. He caused the sun to st...

--------------------------------------------------------------------------------

Global Record 4018:
URL: http://poway.patch.com/groups/editors-picks/p/biggest-bully-in-your-kids-life-might-be-you
Text Snippet: Booby traps to catch sneak-eating. Jabs about jiggly thighs. Teasing about tummies and hints about needing to exercise.
Well-meaning parents trying to subtly address their children's weight issues instead might be the biggest bullies in their kids' lives, according to a recent study in the journal P...

--------------------------------------------------------------------------------

Global Record 4019:
URL: http://rainyside.com/plant_gallery/bulbs/LiliumWhiteStargazer.html
Text Snippet: Sign up for our newsletter
Gardening in the Rainy Zone.
Lilium 'White Stargazer'
Sunset zones: All.
USDA zones: 3-10.
Heat zones: 8-1.
Height: 30-35 inches (76-88 cm).
Star-shaped, white petals recurved at the tips.
Humus rich, slightly acidic, moist, well-drained soil.
In spring, when lilies are at...

--------------------------------------------------------------------------------

Global Record 4020:
URL: http://teach311.wordpress.com/tag/%E7%B1%B3%E8%BB%8D%E5%8D%A0%E9%A0%98%E4%B8%8B/
Text Snippet: Sasamoto, Yukuo. 笹本征男. 1995. Beikoku senryôka no genbaku chôsa—Genbaku kagaikoku ni natta Nihon. 米軍占領下の原爆調査―原爆加害国になった日本 [Atomic Bomb Surveys Under American Occupation: How Japan Became a Nuclear Aggressor]. Shinkansha. 新幹社.
The years it took to develop medical treatment for radiation amounted to a “...

--------------------------------------------------------------------------------

Global Record 4021:
URL: http://universitypost.dk/article/copenhagen-scientists-map-genes-extinct-human
Text Snippet: Scientists can now reconstruct the genes of an ancient human being.
Using a tuft of hair, Copenhagen scientists have sequenced the genome of a 4000-year old Greenlander, giving insight into the traits of ancient peoples, heredity, and the peopling of the Arctic region.
The findings, which are descri...

--------------------------------------------------------------------------------

Global Record 4022:
URL: http://users.telenet.be/d.rijmenants/en/handciphers.htm
Text Snippet: Hand ciphers have always been a compromise between security and practical considerations. Very secure ciphers were often very elaborate, unpractical and prone to errors. This was a disadvantage in tactical circumstances. On the other hand, practical and less complex ciphers were often weak. Nonethel...

--------------------------------------------------------------------------------

Global Record 4023:
URL: http://www.abrazohealth.com/services/mothernewborncare/treatments/resources.aspx?chunkiid=14254
Text Snippet: Loneliness is a universal experience known to every human being on earth. Everyone is potentially susceptible to loneliness, including the rich and famous. Judy Garland once said, "If I'm such a legend, then why am I so lonely? Let me tell you, being a legend is all very well if you've got somebody ...

--------------------------------------------------------------------------------

Global Record 4024:
URL: http://www.acefitness.org/acefit/healthy_living_fit_facts_content.aspx?itemid=2682
Text Snippet: Strength Training for Kids: A Guide for Parents and Teachers
Many parents and physical education teachers have traditionally shied away from strength training with their children or students. However, there is sufficient research to suggest that strength training is a suitable—and safe—option for mo...

--------------------------------------------------------------------------------

Global Record 4025:
URL: http://www.aclu.org/womens-rights/education?quicktabs_content_video_podcasts=1
Text Snippet: The ACLU is working to guarantee all students equal access to educational opportunities and resources in an educational environment free from gender-based stereotypes, violence, and harassment.
Education is the foundation for civic participation, and schools are formative in shaping how children and...

--------------------------------------------------------------------------------

Global Record 4026:
URL: http://www.alphadictionary.com/goodword/date/2012/12/21
Text Snippet: Part of Speech: Verb, transitive
Meaning: 1. To fish by pulling a line through the water. 2 To try to lure or incite someone by passing something where they can see it. 3. (Obsolete) To sing in the manner of a round or simply merrily.
Notes: We have reduced the 14 meanings of today's Good Word to th...

--------------------------------------------------------------------------------

Global Record 4027:
URL: http://www.anagrammer.com/scrabble/jointing
Text Snippet: Log In to Anagrammer
Scrabble word: JOINTING
In which Scrabble dictionary does JOINTING exist?
Definitions of JOINTING in dictionaries:
- verb - fit as if by joints
- verb - provide with a joint
- verb - fasten with a joint
- verb - separate (meat) at the joint
- v - to fit together by means of a ju...

--------------------------------------------------------------------------------

Global Record 4028:
URL: http://www.apologeticspress.com/APContent.aspx?category=9&article=700&topic=62
Text Snippet: Evolution, Intelligent Design, and Testability
As modern science has acquired the ability to see deeper and deeper into the natural world, problems with the waning theory of evolution continue to plague its proponents. A multiplicity of natural, biological systems exhibit complexity that could not h...

--------------------------------------------------------------------------------

Global Record 4029:
URL: http://www.apta.org/PTinMotion/NewsNow/2012/11/20/OnlineAtlases/?blogmonth=1&blogday=16&blogyear=2013&blogid=10737418615
Text Snippet: Centers for Disease Control and Prevention (CDC) has introduced a new online
tool, Diabetes Interactive Atlases, which provides data for
diagnosed diabetes, obesity, and leisure-time physical inactivity at the
national, state, and county levels. The new tool also includes interactive
motion charts s...

--------------------------------------------------------------------------------

Global Record 4030:
URL: http://www.asha.org/Publications/leader/2012/121009/Take-the-Tele-Plunge-at-Your-School.htm
Text Snippet: In two rural Ohio school districts, 120 students are receiving their speech-language treatment via Internet-based videoconferencing. This pilot telepractice project, housed in the Department of Speech Pathology and Audiology at Kent State University (KSU), is one of several efforts seeking to revers...

--------------------------------------------------------------------------------

Global Record 4031:
URL: http://www.astc.org/resource/exhibits/sound/workshop.htm
Text Snippet: A workshop on sound in science center planning and design
Friday, October 5, 2001
In our highly visual society, museum design is often thought of
in terms of architecture, exhibit furniture and devices, lighting,
labels, and signs. Sound gets less attention, and often as a negative
factor, after ins...

--------------------------------------------------------------------------------

Global Record 4032:
URL: http://www.asthma.org.au/Publications/tabid/62/Publications/213/Asthma-Linked-to-Bacterial-Communities.aspx
Text Snippet: In a study led by UCSF team an existence of relationship between asthma and composition of bacterial species, which are present in bronchial airways was revealed.
This finding could suggest new treatment or even potential cures for the common inflammatory disease.
Using new detection methods, resear...

--------------------------------------------------------------------------------

Global Record 4033:
URL: http://www.autotraderclassics.com/car-article/Fire+Protection+and+Prevention-196796.xhtml?conversationId=139600
Text Snippet: Accident damage, unless massive, can be repaired. But if fire takes hold of your car it will destroy it. With so many flammable materials and fuel sources, fire rips through a car in minutes and, by the time the fire brigade arrives, it will be unrestorable.
Fire requires two things: something flamm...

--------------------------------------------------------------------------------

Global Record 4034:
URL: http://www.bellaonline.com/ArticlesP/art62251.asp
Text Snippet: Here are 15 ways kids can benefit from learning meditation techniques:
1. Meditation practice develops strength of character, as the child learns about virtuous living by thinking over the qualities of each virtue. 2. Meditation can help a child learn to think for themselves, and determine a best co...

--------------------------------------------------------------------------------

Global Record 4035:
URL: http://www.ci.sanmateo.ca.us/index.aspx?NID=1443
Text Snippet: Self-Reliance in a Power Outage
People do not usually think of a power outage in the same light as an earthquake. However, when the power is out for a long period of time, citizen requests for fire, police, medical, and other public services will begin to mount. At some point, the increased demand f...

--------------------------------------------------------------------------------

Global Record 4036:
URL: http://www.collectorsweekly.com/articles/an-interview-with-peace-dollar-historian-roger-burdette/
Text Snippet: In this interview, author Roger Burdette discusses the rich history of Peace dollars and explains how these overlooked and affordable coins have much to tell us about the years following World War I. Burdette, who wrote “A Guide Book of Peace Dollars,” also offers insights into the work of such coin...

--------------------------------------------------------------------------------

Global Record 4037:
URL: http://www.digitalcitizen.info/2007/02/19/what-is-free-software-why-does-free-software-matter/
Text Snippet: Richard Stallman discussed Free Software and the future of Free Software in Zagreb on March 9, 2006. Free Software is software that respects a user’s freedom to run, inspect, share, and modify the software for any purpose at any time. Non-free software, by contrast, denies users these freedoms. Even...

--------------------------------------------------------------------------------

Global Record 4038:
URL: http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200025917
Text Snippet: 2. Phyllostachys makinoi Hayata, Icon. Pl. Formosan. 5: 250. 1915.
台湾桂竹 tai wan gui zhu
Culms 10–20 m, 3–8 cm in diam.; internodes to 40 cm, initially thinly white powdery, glabrous, with minute holes or crystalline spots (visible under 10 × lens); wall to 1 cm thick; nodal ridge as prominent as she...

--------------------------------------------------------------------------------

Global Record 4039:
URL: http://www.intelihealth.com/IH/ihtIH/EMIHC267/9339/31219.html
Text Snippet: What Is It?
A meniscus is a disk-shaped piece of cartilage that acts as a shock absorber inside a joint. Each knee has one lateral meniscus under the outer knob of the thighbone and one medial meniscus under the inner knob of the thighbone. Each meniscus acts as a natural cushion between the thighbo...

--------------------------------------------------------------------------------

Global Record 4040:
URL: http://www.itec.suny.edu/scsys/vms/ovmsdoc073/V73/6489/6489pro_007.html
Text Snippet: |Document revision date: 30 March 2001|
The following keys recall commands:
The following keys control cursor position:
The following keys control screen display:

# 10) Resuming 4000 documents in, with a custom DataLoader binning

In [10]:
class ShardDataset(Dataset):
    def __init__(self, shards_dir):
        self.shards_dir = shards_dir

    def __len__(self):
        return max_shards

    def __getitem__(self, idx):
        shard_file = os.path.join(self.shards_dir,
                                  f"shard_{idx:03d}.jsonl")
        records = []
        with open(shard_file, "r", encoding="utf-8") as f:
            for line in f:
                records.append(json.loads(line))
        return records

dataset = ShardDataset(shards_output_dir)

shard_index_to_read = 4
global_start_index = shard_index_to_read * records_per_shard

print(f"Reading shard {shard_index_to_read} via dataset[idx]... starts at global record {global_start_index + 1}\n")

# Retrieve all records for the specific shard file
shard_records = dataset[shard_index_to_read]

for i, record in enumerate(shard_records):
    global_record_num = global_start_index + i + 1

    print(f"Global Record {global_record_num}:")
    print(f"URL: {record['url']}")
    print(f"Text Snippet: {record['text'][:300]}...\n")
    print("-" * 80 + "\n")

Reading shard 4 via dataset[idx]... starts at global record 4001

Global Record 4001:
URL: http://www.usaid.gov/results-data/success-stories/saving-newborns-rural-afghanistan
Text Snippet: Miriam has four children, although she has given birth six times. Two infants unfortunately died within days of birth. However, her most recent birth was different in that Miriam and her female relatives had learned from the local female community health worker (CHW) about the importance of keeping ...

--------------------------------------------------------------------------------

Global Record 4002:
URL: http://apnews.excite.com/article/20110219/D9LG45NO0.html
Text Snippet: Cosmic census finds crowd of planets in our galaxy
Feb 19, 5:23 PM (ET)
By SETH BORENSTEIN
WASHINGTON (AP) - Scientists have estimated the first cosmic census of planets in our galaxy and the numbers are astronomical: at least 50 billion planets in the Milky Way.
At least 500 million of those planet...

--------------------------------------------------------------------------------

Global Record 4003:
URL: http://asopa.typepad.com/asopa_people/2012/10/a-poets-journey-3-poetic-inspiration-from-human-experience.html
Text Snippet: ‘A POEM SHOULD BE PALPABLE AND MUTE / As a globed fruit’, says Archibald MacLeish in his poem Ars Poetica [‘The art of poetry’].
Poems are very often inspired by our experiences in life and it is part of the challenge of writing poetry to find ways of expressing our thoughts and feelings without men...

--------------------------------------------------------------------------------

Global Record 4004:
URL: http://blog.prideinplymouth.org.uk/category/featured/alan-turing/
Text Snippet: Lesbian Gay Bisexual Trans History Month takes place every year in February. It celebrates the lives and achievements of the LGBT community. 2013 is dedicated to Maths, science and engineering.
LGBT History Month UK have put together a publication that features Lesbian, Gay, Bisexual and Trans pione...

--------------------------------------------------------------------------------

Global Record 4005:
URL: http://centria.di.fct.unl.pt/projects/view.php?code=6232b5ec42f9dc0f25f4f45fd1002a86&t=o&cscd=85ff861d6c46e37ebe256c211f0d0a25
Text Snippet: Software is ubiquitous in modern day life. Software is used in all personal computing devices, but it also supports the Internet and all existing communication networks. Software is also ubiquitous in all forms of transportation, including avionics, automotive, railways and shipping. Software is als...

--------------------------------------------------------------------------------

Global Record 4006:
URL: http://divisbyzero.com/2008/12/18/sharkovskys-theorem/
Text Snippet: In this post I would like to share one of the most surprising, remarkable, and beautiful results in the study of discrete dynamical systems. It relates to an unusual ordering of the positive integers:
First, some definitions. The basic object of study in a discrete dynamical system is the orbit. Let...

--------------------------------------------------------------------------------

Global Record 4007:
URL: http://en.m.wikibooks.org/wiki/Calculus/Continuity
Text Snippet: We are now ready to define the concept of a function being continuous. The idea is that we want to say that a function is continuous if you can draw its graph without taking your pencil off the page. But sometimes this will be true for some parts of a graph but not for others. Therefore, we want to ...

--------------------------------------------------------------------------------

Global Record 4008:
URL: http://en.wikipedia.org/wiki/Second_Constitutional_Era_(Ottoman_Empire)
Text Snippet: Second Constitutional Era
||This article needs additional citations for verification. (July 2012)|
|Part of a series on the|
|History of Turkey|
The Second Constitutional Era (ايکنجى مشروطيت دورى İkinci Meşrûtiyyet Devri) of the Ottoman Empire began shortly after Sultan Abdülhamid II restored the co...

--------------------------------------------------------------------------------

Global Record 4009:
URL: http://english.people.com.cn/90782/8120039.html
Text Snippet: |The warning label on cigarette packaging (U.S. HHS)|
Key Words:cancer;disease; health
>>Failed again? Quit smoking could not be hard
>>Women who quit smoking before middle age can live a decade longer: study
>>Quit smoking before age 40 greatly reduces death risk: study
SHANGHAI'S cancer rate remai...

--------------------------------------------------------------------------------

Global Record 4010:
URL: http://fun.familyeducation.com/hanukkah/passover/55218.html
Text Snippet: Wooden Star of David
Activity for an individual child
Age group: 18-40 months
Duration of activity: 20 minutes
- 6 craft sticks
- White craft glue
- Blue and white tempera paints
- 2 shallow pie tins
Your child will be learning about shapes and geometry while she makes this well-known symbol.
- Show...

--------------------------------------------------------------------------------

Global Record 4011:
URL: http://health.nytimes.com/health/guides/disease/pharyngitis-viral/news-and-features.html
Text Snippet: May 21, 2013
Pharyngitis - Viral
News & Features
Doctors and patients don’t always communicate well, with serious consequences, says Jerome Groopman.
A few studies have provided scientific evidence that a chill won't cause a cold, but perhaps the answer is not so clear cut.
Many experts say that few...

--------------------------------------------------------------------------------

Global Record 4012:
URL: http://jdp-news.blogspot.com/2010_07_01_archive.html
Text Snippet: Patti challenged us to use or adapt the following form to create a poem:
When ____________ you'll find ___________
That __________________ to make
Patti gave us an example, borrowed from Word After Word After Word, by Patricia MacLachlan (p 36):
When cracked you'll find inside
That tuck in snugly to...

--------------------------------------------------------------------------------

Global Record 4013:
URL: http://kwit.org/post/us-officials-syria-has-prepared-several-dozen-chemical-bombs
Text Snippet: Fri December 14, 2012
U.S. Officials: Syria Has Prepared Several Dozen Chemical Bombs
U.S. and allied officials say the forces of embattled Syrian President Bashar Assad have prepared several dozen bombs and shells loaded with the lethal chemical sarin.
The number is a larger estimate than has previ...

--------------------------------------------------------------------------------

Global Record 4014:
URL: http://labtestsonline.org/news/120323glucose-testing/
Text Snippet: A new clinical practice guideline published in the January 2012 issue of the Journal of Clinical Endocrinology and Metabolism includes the recommendation that everyone admitted to the hospital have blood glucose testing performed. The evidence-based guideline was developed by a panel convened by The...

--------------------------------------------------------------------------------

Global Record 4015:
URL: http://moadoph.gov.au/exhibitions/online/dismissed/epilogue.html
Text Snippet: Thirty years on, the rules of the Constitution which allowed for the dismissal of the Whitlam Labor Government remain unchanged. The different readings of the Constitution put forward by Gough Whitlam and Malcolm Fraser in 1975, and of the conventions surrounding the operations of the Constitution, ...

--------------------------------------------------------------------------------

Global Record 4016:
URL: http://npiweb.com/west/ResourceCenter/tabid/10568/CategoryID/17/resourceID/274/Default.aspx
Text Snippet: To help children make the transition from an old home to a new, try to ease some of the initial fear or apprehension by offering information.
- Look up things about the new home online, on maps or in reference books. Make a scavenger hunt or other game out of the activity.
- Have a special goodbye o...

--------------------------------------------------------------------------------

Global Record 4017:
URL: http://orthodoxwiki.org/index.php?title=Joshua_of_Navi&direction=prev&oldid=102227
Text Snippet: Joshua of Navi
Joshua of Navi, was born of the tribe of Ephraim in Egypt, in the seventeenth century before Christ. When he was eighty-five years of age, he became the successor of Moses.  He restrained the flow of the River Jordan and allowed the Israelites to cross on foot. He caused the sun to st...

--------------------------------------------------------------------------------

Global Record 4018:
URL: http://poway.patch.com/groups/editors-picks/p/biggest-bully-in-your-kids-life-might-be-you
Text Snippet: Booby traps to catch sneak-eating. Jabs about jiggly thighs. Teasing about tummies and hints about needing to exercise.
Well-meaning parents trying to subtly address their children's weight issues instead might be the biggest bullies in their kids' lives, according to a recent study in the journal P...

--------------------------------------------------------------------------------

Global Record 4019:
URL: http://rainyside.com/plant_gallery/bulbs/LiliumWhiteStargazer.html
Text Snippet: Sign up for our newsletter
Gardening in the Rainy Zone.
Lilium 'White Stargazer'
Sunset zones: All.
USDA zones: 3-10.
Heat zones: 8-1.
Height: 30-35 inches (76-88 cm).
Star-shaped, white petals recurved at the tips.
Humus rich, slightly acidic, moist, well-drained soil.
In spring, when lilies are at...

--------------------------------------------------------------------------------

Global Record 4020:
URL: http://teach311.wordpress.com/tag/%E7%B1%B3%E8%BB%8D%E5%8D%A0%E9%A0%98%E4%B8%8B/
Text Snippet: Sasamoto, Yukuo. 笹本征男. 1995. Beikoku senryôka no genbaku chôsa—Genbaku kagaikoku ni natta Nihon. 米軍占領下の原爆調査―原爆加害国になった日本 [Atomic Bomb Surveys Under American Occupation: How Japan Became a Nuclear Aggressor]. Shinkansha. 新幹社.
The years it took to develop medical treatment for radiation amounted to a “...

--------------------------------------------------------------------------------

Global Record 4021:
URL: http://universitypost.dk/article/copenhagen-scientists-map-genes-extinct-human
Text Snippet: Scientists can now reconstruct the genes of an ancient human being.
Using a tuft of hair, Copenhagen scientists have sequenced the genome of a 4000-year old Greenlander, giving insight into the traits of ancient peoples, heredity, and the peopling of the Arctic region.
The findings, which are descri...

--------------------------------------------------------------------------------

Global Record 4022:
URL: http://users.telenet.be/d.rijmenants/en/handciphers.htm
Text Snippet: Hand ciphers have always been a compromise between security and practical considerations. Very secure ciphers were often very elaborate, unpractical and prone to errors. This was a disadvantage in tactical circumstances. On the other hand, practical and less complex ciphers were often weak. Nonethel...

--------------------------------------------------------------------------------

Global Record 4023:
URL: http://www.abrazohealth.com/services/mothernewborncare/treatments/resources.aspx?chunkiid=14254
Text Snippet: Loneliness is a universal experience known to every human being on earth. Everyone is potentially susceptible to loneliness, including the rich and famous. Judy Garland once said, "If I'm such a legend, then why am I so lonely? Let me tell you, being a legend is all very well if you've got somebody ...

--------------------------------------------------------------------------------

Global Record 4024:
URL: http://www.acefitness.org/acefit/healthy_living_fit_facts_content.aspx?itemid=2682
Text Snippet: Strength Training for Kids: A Guide for Parents and Teachers
Many parents and physical education teachers have traditionally shied away from strength training with their children or students. However, there is sufficient research to suggest that strength training is a suitable—and safe—option for mo...

--------------------------------------------------------------------------------

Global Record 4025:
URL: http://www.aclu.org/womens-rights/education?quicktabs_content_video_podcasts=1
Text Snippet: The ACLU is working to guarantee all students equal access to educational opportunities and resources in an educational environment free from gender-based stereotypes, violence, and harassment.
Education is the foundation for civic participation, and schools are formative in shaping how children and...

--------------------------------------------------------------------------------

Global Record 4026:
URL: http://www.alphadictionary.com/goodword/date/2012/12/21
Text Snippet: Part of Speech: Verb, transitive
Meaning: 1. To fish by pulling a line through the water. 2 To try to lure or incite someone by passing something where they can see it. 3. (Obsolete) To sing in the manner of a round or simply merrily.
Notes: We have reduced the 14 meanings of today's Good Word to th...

--------------------------------------------------------------------------------

Global Record 4027:
URL: http://www.anagrammer.com/scrabble/jointing
Text Snippet: Log In to Anagrammer
Scrabble word: JOINTING
In which Scrabble dictionary does JOINTING exist?
Definitions of JOINTING in dictionaries:
- verb - fit as if by joints
- verb - provide with a joint
- verb - fasten with a joint
- verb - separate (meat) at the joint
- v - to fit together by means of a ju...

--------------------------------------------------------------------------------

Global Record 4028:
URL: http://www.apologeticspress.com/APContent.aspx?category=9&article=700&topic=62
Text Snippet: Evolution, Intelligent Design, and Testability
As modern science has acquired the ability to see deeper and deeper into the natural world, problems with the waning theory of evolution continue to plague its proponents. A multiplicity of natural, biological systems exhibit complexity that could not h...

--------------------------------------------------------------------------------

Global Record 4029:
URL: http://www.apta.org/PTinMotion/NewsNow/2012/11/20/OnlineAtlases/?blogmonth=1&blogday=16&blogyear=2013&blogid=10737418615
Text Snippet: Centers for Disease Control and Prevention (CDC) has introduced a new online
tool, Diabetes Interactive Atlases, which provides data for
diagnosed diabetes, obesity, and leisure-time physical inactivity at the
national, state, and county levels. The new tool also includes interactive
motion charts s...

--------------------------------------------------------------------------------

Global Record 4030:
URL: http://www.asha.org/Publications/leader/2012/121009/Take-the-Tele-Plunge-at-Your-School.htm
Text Snippet: In two rural Ohio school districts, 120 students are receiving their speech-language treatment via Internet-based videoconferencing. This pilot telepractice project, housed in the Department of Speech Pathology and Audiology at Kent State University (KSU), is one of several efforts seeking to revers...

--------------------------------------------------------------------------------

Global Record 4031:
URL: http://www.astc.org/resource/exhibits/sound/workshop.htm
Text Snippet: A workshop on sound in science center planning and design
Friday, October 5, 2001
In our highly visual society, museum design is often thought of
in terms of architecture, exhibit furniture and devices, lighting,
labels, and signs. Sound gets less attention, and often as a negative
factor, after ins...

--------------------------------------------------------------------------------

Global Record 4032:
URL: http://www.asthma.org.au/Publications/tabid/62/Publications/213/Asthma-Linked-to-Bacterial-Communities.aspx
Text Snippet: In a study led by UCSF team an existence of relationship between asthma and composition of bacterial species, which are present in bronchial airways was revealed.
This finding could suggest new treatment or even potential cures for the common inflammatory disease.
Using new detection methods, resear...

--------------------------------------------------------------------------------

Global Record 4033:
URL: http://www.autotraderclassics.com/car-article/Fire+Protection+and+Prevention-196796.xhtml?conversationId=139600
Text Snippet: Accident damage, unless massive, can be repaired. But if fire takes hold of your car it will destroy it. With so many flammable materials and fuel sources, fire rips through a car in minutes and, by the time the fire brigade arrives, it will be unrestorable.
Fire requires two things: something flamm...

--------------------------------------------------------------------------------

Global Record 4034:
URL: http://www.bellaonline.com/ArticlesP/art62251.asp
Text Snippet: Here are 15 ways kids can benefit from learning meditation techniques:
1. Meditation practice develops strength of character, as the child learns about virtuous living by thinking over the qualities of each virtue. 2. Meditation can help a child learn to think for themselves, and determine a best co...

--------------------------------------------------------------------------------

Global Record 4035:
URL: http://www.ci.sanmateo.ca.us/index.aspx?NID=1443
Text Snippet: Self-Reliance in a Power Outage
People do not usually think of a power outage in the same light as an earthquake. However, when the power is out for a long period of time, citizen requests for fire, police, medical, and other public services will begin to mount. At some point, the increased demand f...

--------------------------------------------------------------------------------

Global Record 4036:
URL: http://www.collectorsweekly.com/articles/an-interview-with-peace-dollar-historian-roger-burdette/
Text Snippet: In this interview, author Roger Burdette discusses the rich history of Peace dollars and explains how these overlooked and affordable coins have much to tell us about the years following World War I. Burdette, who wrote “A Guide Book of Peace Dollars,” also offers insights into the work of such coin...

--------------------------------------------------------------------------------

Global Record 4037:
URL: http://www.digitalcitizen.info/2007/02/19/what-is-free-software-why-does-free-software-matter/
Text Snippet: Richard Stallman discussed Free Software and the future of Free Software in Zagreb on March 9, 2006. Free Software is software that respects a user’s freedom to run, inspect, share, and modify the software for any purpose at any time. Non-free software, by contrast, denies users these freedoms. Even...

--------------------------------------------------------------------------------

Global Record 4038:
URL: http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200025917
Text Snippet: 2. Phyllostachys makinoi Hayata, Icon. Pl. Formosan. 5: 250. 1915.
台湾桂竹 tai wan gui zhu
Culms 10–20 m, 3–8 cm in diam.; internodes to 40 cm, initially thinly white powdery, glabrous, with minute holes or crystalline spots (visible under 10 × lens); wall to 1 cm thick; nodal ridge as prominent as she...

--------------------------------------------------------------------------------

Global Record 4039:
URL: http://www.intelihealth.com/IH/ihtIH/EMIHC267/9339/31219.html
Text Snippet: What Is It?
A meniscus is a disk-shaped piece of cartilage that acts as a shock absorber inside a joint. Each knee has one lateral meniscus under the outer knob of the thighbone and one medial meniscus under the inner knob of the thighbone. Each meniscus acts as a natural cushion between the thighbo...

--------------------------------------------------------------------------------

Global Record 4040:
URL: http://www.itec.suny.edu/scsys/vms/ovmsdoc073/V73/6489/6489pro_007.html
Text Snippet: |Document revision date: 30 March 2001|
The following keys recall commands:
The following keys control cursor position:
The following keys control screen display:

# 11) Extract and quality score a web page

In [ ]:
assert False, "did you fetch your website, extracted HTML and compared quality?"

AssertionError: did you fetch your website, extracted HTML and compared quality?

In [14]:
#@title Answer (setup if you didn't want to run the whole notebook)

#@title Answer

import urllib.request
import html
from html.parser import HTMLParser
import trafilatura
import justext
from IPython.display import display, HTML
import fasttext
from huggingface_hub import hf_hub_download
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

class NaiveHTMLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self.fed = []
        self.skip_tags = {"script", "style", "noscript"}
        self.current_skip = False
    def handle_starttag(self, tag, attrs):
        if tag in self.skip_tags:
            self.current_skip = True
    def handle_endtag(self, tag):
        if tag in self.skip_tags:
            self.current_skip = False
    def handle_data(self, data):
        if not self.current_skip:
            self.fed.append(data)
    def get_text(self):
        return " ".join("".join(self.fed).split())

print("Loading quality classifiers...")
# Setup DCLM Classifier
dclm_model_path = hf_hub_download(
    repo_id="mlfoundations/fasttext-oh-eli5",
    filename="openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train.bin",
)
dclm_classifier = fasttext.load_model(dclm_model_path)

def dclm_quality_score(text, classifier=dclm_classifier):
    cleaned = text.replace("\n", " ").strip()[:5000]
    predictions = classifier.f.predict(cleaned, 1, 0.0, "")
    probability, label = predictions[0]
    if label == "__label__hq":
        return probability
    else:
        return 1.0 - probability

# Setup FineWeb-Edu Classifier
fineweb_classifier_name = "HuggingFaceFW/fineweb-edu-classifier"
fineweb_tokenizer = AutoTokenizer.from_pretrained(fineweb_classifier_name)
fineweb_quality_model = AutoModelForSequenceClassification.from_pretrained(fineweb_classifier_name)
fineweb_quality_model.eval()

def fineweb_edu_quality_score(text, tokenizer=fineweb_tokenizer, model=fineweb_quality_model):
    truncated = text[:2000]
    tokens = tokenizer(truncated, return_tensors="pt", padding=True, truncation=True, max_length=512)
    with torch.no_grad():
        score = model(**tokens).logits.squeeze(-1).item()
    return round(score, 4)

Loading quality classifiers...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [15]:
#@title Answer
# 1. Define the target URL and fetch the HTML
target_url = "https://en.wikipedia.org/wiki/Deep_learning"
print(f"\nFetching HTML from: {target_url}")

req = urllib.request.Request(target_url, headers={'User-Agent': 'Mozilla/5.0'})
with urllib.request.urlopen(req) as response:
    raw_bytes = response.read()
    raw_text = raw_bytes.decode('utf-8', errors='replace')

# 2. Extract text using Trafilatura
print("Extracting using Trafilatura...")
ext_traf = trafilatura.extract(raw_text) or "No content extracted"

# 3. Extract text using Justext
print("Extracting using Justext...")
paragraphs = justext.justext(raw_bytes, justext.get_stoplist("English"))
ext_just = "\n".join([p.text for p in paragraphs if not p.is_boilerplate]) or "No content extracted"

# 4. Extract text using the Naive HTML Stripper defined earlier
print("Extracting using Naive HTML Stripper...")
my_stripper = NaiveHTMLStripper()
my_stripper.feed(raw_text)
ext_naive = my_stripper.get_text()

# 5. Quality Filtering
print("Calculating quality scores...")
traf_dclm = dclm_quality_score(ext_traf)
just_dclm = dclm_quality_score(ext_just)
naive_dclm = dclm_quality_score(ext_naive)

traf_fw = fineweb_edu_quality_score(ext_traf)
just_fw = fineweb_edu_quality_score(ext_just)
naive_fw = fineweb_edu_quality_score(ext_naive)

# 6. Display a side-by-side comparison table
print("Generating comparison table...\n")
def truncate_and_escape(text, length=300):
    safe_text = html.escape((text or "")[:length])
    return safe_text + ("..." if len(text or "") > length else "")

table_html = f"""
<table style="width:100%; text-align:left; border-collapse: collapse; border: 1px solid #ccc; table-layout: fixed;">
    <tr style="background-color: #f2f2f2;">
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Trafilatura</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Justext</th>
        <th style="padding: 10px; border: 1px solid #ccc; width: 33.33%;">Naive HTML Stripper</th>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_traf)}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_just)}</pre></td>
        <td style="padding: 10px; border: 1px solid #ccc; vertical-align: top;"><pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 12px; font-family: monospace;">{truncate_and_escape(ext_naive)}</pre></td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_traf):,}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_just):,}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>Characters:</b> {len(ext_naive):,}</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {traf_dclm:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {just_dclm:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>DCLM Score:</b> {naive_dclm:.4f}</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {traf_fw:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {just_fw:.4f}</td>
        <td style="padding: 10px; border: 1px solid #ccc;"><b>FineWeb-Edu Score:</b> {naive_fw:.4f}</td>
    </tr>
</table>
"""
display(HTML(table_html))

Fetching HTML from: https://en.wikipedia.org/wiki/Deep_learning
Extracting using Trafilatura...
Extracting using Justext...
Extracting using Naive HTML Stripper...
Calculating quality scores...
Generating comparison table...